// netlify.toml
[build]
  command = "yarn build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"

[[redirects]]
from = “/*”
to = “/index.html”
status = 200

[[headers]]
for = “/"
[headers.values]
Access-Control-Allow-Origin = "”
